[package]
name = "nowhear"
version = "0.1.0"
edition = "2024"
authors = ["Akiomi Kamakura <akiomik@gmail.com>"]
description = "Cross-platform media playback information watcher"
repository = "https://github.com/akiomik/nowhear"
keywords = ["media", "music", "playback", "mpris", "nowplaying"]
categories = ["multimedia", "os"]

[dependencies]
futures = "0.3"
thiserror = "1.0"
tokio = { version = "1.0", features = ["macros", "process", "rt", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2.0"
zbus = "4.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Media_Control",
    "Storage_Streams",
    "Foundation",
] }

[[example]]
name = "stream"
path = "examples/stream.rs"
